### PR TITLE
Updated Lesson 0

### PR DESCRIPTION
**Pull request by emmalieb**
Latest update to Lesson 0, minor changes including answers to questions and enabling cloud dataset

### CODE REVIEW

**Comment by emmalieb** [comment]
<p>oops yes sorry, removed</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/15/discussion/#comment-1636911077'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by emmalieb** [comment]
<p>okay, updated to use sexidecimal and removed the conversion in the text. added text to express your second point as well. </p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/15/discussion/#comment-1636911079'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by emmalieb** [comment]
<p>okay</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/15/discussion/#comment-1636911084'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by emmalieb** [comment]
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/15/discussion/#comment-1636911097'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by emmalieb** [comment]
<p>okay</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/15/discussion/#comment-1636911103'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ttdu** [comment]
That merge conflict was not reconcilable with my git skills, so I've merged your changes through a new PR

**Pull request closed without merging**
