### PR TITLE
Astroseismology notebooks

### PR DESCRIPTION
**Pull request by lsegev-stsci**
First draft of astroseismology notebooks

### CODE REVIEW

**Comment by lsegev-stsci** [comment]
<p>AWS not mentioned in notebook anymore</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/8/discussion/#comment-1627806026'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by lsegev-stsci** [comment]
<p>Note added</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/8/discussion/#comment-1627806029'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by lsegev-stsci** [comment]
<p>Comment added</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/8/discussion/#comment-1627806034'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by lsegev-stsci** [comment]
<p>Change made</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/8/discussion/#comment-1627806037'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by lsegev-stsci** [comment]
<p>Text moved, all links to here replaced with page title/description, and commentary on timing the cell added.</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/8/discussion/#comment-1627806041'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by lsegev-stsci** [comment]
<p>Paragraph reworded based on feedback</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/8/discussion/#comment-1627806046'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by lsegev-stsci** [comment]
<p>Comment added</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/8/discussion/#comment-1627806051'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by lsegev-stsci** [comment]
<p>Narrative added before all data retrieval methods</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/8/discussion/#comment-1627806063'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by lsegev-stsci** [comment]
<p>All links to 'here' were replaced by the site description/title</p><p> </p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/8/discussion/#comment-1627806068'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by lsegev-stsci** [comment]
<p>Link to here replaced with descriptor, aperture mask paragraph moved up</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/8/discussion/#comment-1627806073'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by lsegev-stsci** [comment]
<p>Narrative added emphasizing that the light curves are pre-generated.</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/8/discussion/#comment-1627806079'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by lsegev-stsci** [comment]
<p>Flattening it didn't make a significant difference here, so it was removed</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/8/discussion/#comment-1627806084'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by lsegev-stsci** [comment]
<p>Slipped up; rephrased it so as not to use pronouns</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/8/discussion/#comment-1627806089'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by lsegev-stsci** [comment]
<p>Feedback incorporated in new version of diagram, chose to keep the telescope and call it cloud archive</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/8/discussion/#comment-1627806097'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by lsegev-stsci** [comment]
<p>Was changed to just one file. By itself it is significantly faster than plain lightkurve and can be applied to other, slightly faster import ways, however wouldn't be worth it if the user wants direct to TPF or a light curve.</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/8/discussion/#comment-1627806102'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by lsegev-stsci** [comment]
<p>Was a mistake when shifting between potential targets but not changing threshold limits, the primary stellar transits are now showing up as subtracted in the plots.</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/8/discussion/#comment-1627806116'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by lsegev-stsci** [comment]
<p>Focus on lightkurve specifically removed</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/8/discussion/#comment-1627806101'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by lsegev-stsci** [comment]
<p>Remove outliers method taken off, turns out it did not have much of an effect either way</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/8/discussion/#comment-1627806111'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by lsegev-stsci** [comment]
<p>This section is still using the default pipeline, narration was edited to make that more clear and source for period added and linked. In the later section when the notebook diverges from the pipeline, a comparison to pipeline accuracy section was added and found almost double as accurate (for this example, in general still significantly more accurate).</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/8/discussion/#comment-1627806107'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by lsegev-stsci** [comment]
<p>While file names can be retrieved with astroquery, they can also be written by filling in the format guide with the appropriate name, file type, CCD, etc. which was actually how fs.get() was first used when writing the notebook. Upon looking over all the methods of data retrieval after and realizing astroquery returned the same format, that paragraph section was added. </p><p>Also, testing the search and download in separate boxes does not change the difference that significantly and rerunning astroquery on the same target does not work for comparison's sake as it is consistently significantly faster (almost instant) the second time, like it 'remembers' from the first search.</p><p>An additional paragraph can be added breaking down the formatting described in the link and what to fill in, if wanted.</p>

---

 <a href='https://app.reviewnb.com/spacetelescope/project-tikebook/pull/8/discussion/#comment-1627806094'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by ttdu — APPROVED** [review]
Merging into the repo

**Pull request merged**
